title: The First Blog
author: Preston Muonio
email: preston.muonio@gmail.com
theme: minima
description: 
  I'm learning how to use github! This is a fun new tool for me. Right now im learning how to use GitHub pages.
  It is a tool for creating websites to showcase your proggress very easily! 

